### ISSUE TITLE
Amount of apples in replay

### ISSUE THREAD

**Issue by sunehs** [elmadev/elmajs#184]
Would be useful to be able to get amount of apples in a replay. As far as I know though it requires knowing at least amount of killers in the level. Would be fine for me if that's just a parameter you give. In elma.online where I use the older node-elma currently we have amount of killers and apples in the db already. For reference this is the getRecInfo.php that I updated to include this feature: https://gist.github.com/sunehs/7690b1374439a2175fdef76de1e01740

**Comment by hexjelly** [comment]
If you just need the amount of apples taken, then that's possible to get from just the replay (and if you don't care to check if all were taken or not). I guess I could add that feature at least
